[package]
name = "crate-study"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["unstable-locales"] }
jsonwebtoken = "9.3.0"
serde = { version = "1.0.208", features = ["derive"] }
